# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=portfolio
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=123456

# Expose the default MySQL port
EXPOSE 3306
